# Generated by Django 4.1.6 on 2023-04-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_authorcategory_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='subscribers',
            field=models.ManyToManyField(through='news.AuthorCategory', to='news.category'),
        ),
    ]
