# Generated by Django 4.1.6 on 2023-04-20 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_author_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='subscribers',
        ),
        migrations.AlterField(
            model_name='authorcategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='news.AuthorCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
