# Generated by Django 4.1.6 on 2023-11-26 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_rename_author_authorcategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', through='news.AuthorCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
